
IF DB_ID(N'KrishavERPv1') IS NULL
    CREATE DATABASE KrishavERPv1;
GO
USE KrishavERPv1;
GO

CREATE TABLE AppUsers(
 Id INT IDENTITY PRIMARY KEY,
 Username NVARCHAR(256) NOT NULL UNIQUE,
 PasswordHash NVARCHAR(MAX) NOT NULL,
 DisplayName NVARCHAR(256) NOT NULL,
 IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE Doctors(
 Id INT IDENTITY PRIMARY KEY,
 Name NVARCHAR(256) NOT NULL,
 Specialisation NVARCHAR(MAX) NOT NULL,
 ConsultationCharge DECIMAL(18,2) NOT NULL,
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Patients(
 Id INT IDENTITY PRIMARY KEY,
 PatientCode NVARCHAR(100) NOT NULL UNIQUE,
 Name NVARCHAR(256) NOT NULL,
 Age INT NOT NULL,
 Gender NVARCHAR(30) NOT NULL,
 Phone NVARCHAR(50) NOT NULL,
 IsDeleted BIT NOT NULL DEFAULT 0,
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_Patients_Name_Phone ON Patients(Name,Phone);

CREATE TABLE OpdVisits(
 Id INT IDENTITY PRIMARY KEY,
 VisitNumber NVARCHAR(100) NOT NULL UNIQUE,
 PatientId INT NOT NULL,
 DoctorId INT NULL,
 IsEmergency BIT NOT NULL DEFAULT 0,
 BloodPressure NVARCHAR(50) NULL,
 TemperatureC DECIMAL(18,2) NULL,
 Problem NVARCHAR(MAX) NULL,
 VisitDateUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 ConvertedToIpd BIT NOT NULL DEFAULT 0,
 IsCancelled BIT NOT NULL DEFAULT 0,
 FOREIGN KEY(PatientId) REFERENCES Patients(Id),
 FOREIGN KEY(DoctorId) REFERENCES Doctors(Id)
);
CREATE INDEX IX_OpdVisits_Patient_Date ON OpdVisits(PatientId,VisitDateUtc DESC);

CREATE TABLE PatientDocuments(
 Id INT IDENTITY PRIMARY KEY,
 PatientId INT NOT NULL,
 Category NVARCHAR(100) NOT NULL,
 FileName NVARCHAR(512) NOT NULL,
 StoredPath NVARCHAR(1024) NOT NULL,
 UploadedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(PatientId) REFERENCES Patients(Id)
);

CREATE TABLE Bills(
 Id INT IDENTITY PRIMARY KEY,
 BillNumber NVARCHAR(100) NOT NULL UNIQUE,
 PatientId INT NULL,
 BillType NVARCHAR(50) NOT NULL,
 GrossAmount DECIMAL(18,2) NOT NULL,
 DiscountPercent DECIMAL(8,2) NOT NULL DEFAULT 0,
 DiscountAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
 NetAmount DECIMAL(18,2) NOT NULL,
 PaidAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
 Status NVARCHAR(50) NOT NULL DEFAULT 'Unpaid',
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(PatientId) REFERENCES Patients(Id)
);
CREATE INDEX IX_Bills_Status_Type_Date ON Bills(Status,BillType,CreatedAtUtc DESC);

CREATE TABLE BillItems(
 Id INT IDENTITY PRIMARY KEY,
 BillId INT NOT NULL,
 Description NVARCHAR(512) NOT NULL,
 Quantity INT NOT NULL,
 UnitPrice DECIMAL(18,2) NOT NULL,
 Amount DECIMAL(18,2) NOT NULL,
 ReferenceType NVARCHAR(100) NULL,
 ReferenceId INT NULL,
 FOREIGN KEY(BillId) REFERENCES Bills(Id) ON DELETE CASCADE
);

CREATE TABLE Payments(
 Id INT IDENTITY PRIMARY KEY,
 BillId INT NOT NULL,
 Amount DECIMAL(18,2) NOT NULL,
 Mode NVARCHAR(50) NOT NULL,
 Reference NVARCHAR(256) NULL,
 PaidAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(BillId) REFERENCES Bills(Id) ON DELETE CASCADE
);

CREATE TABLE WardBeds(
 Id INT IDENTITY PRIMARY KEY,
 BedNumber NVARCHAR(100) NOT NULL UNIQUE,
 IsOccupied BIT NOT NULL DEFAULT 0,
 CurrentIpdAdmissionId INT NULL
);

CREATE TABLE IpdAdmissions(
 Id INT IDENTITY PRIMARY KEY,
 AdmissionNumber NVARCHAR(100) NOT NULL UNIQUE,
 PatientId INT NOT NULL,
 SourceOpdVisitId INT NULL,
 DoctorId INT NOT NULL,
 BedId INT NOT NULL,
 AdmittedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 DischargedAtUtc DATETIME2 NULL,
 Status NVARCHAR(50) NOT NULL DEFAULT 'Admitted',
 FOREIGN KEY(PatientId) REFERENCES Patients(Id),
 FOREIGN KEY(SourceOpdVisitId) REFERENCES OpdVisits(Id),
 FOREIGN KEY(DoctorId) REFERENCES Doctors(Id),
 FOREIGN KEY(BedId) REFERENCES WardBeds(Id)
);

CREATE TABLE IpdVitals(
 Id INT IDENTITY PRIMARY KEY,
 IpdAdmissionId INT NOT NULL,
 BloodPressure NVARCHAR(50),
 TemperatureC DECIMAL(18,2),
 Pulse INT,
 Spo2 DECIMAL(18,2),
 Notes NVARCHAR(MAX),
 RecordedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(IpdAdmissionId) REFERENCES IpdAdmissions(Id)
);

CREATE TABLE IpdDoctorNotes(
 Id INT IDENTITY PRIMARY KEY,
 IpdAdmissionId INT NOT NULL,
 DoctorId INT NOT NULL,
 Suggestion NVARCHAR(MAX) NOT NULL,
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(IpdAdmissionId) REFERENCES IpdAdmissions(Id),
 FOREIGN KEY(DoctorId) REFERENCES Doctors(Id)
);

CREATE TABLE IpdNursingNotes(
 Id INT IDENTITY PRIMARY KEY,
 IpdAdmissionId INT NOT NULL,
 ActionTaken NVARCHAR(MAX) NOT NULL,
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(IpdAdmissionId) REFERENCES IpdAdmissions(Id)
);

CREATE TABLE IpdDocuments(
 Id INT IDENTITY PRIMARY KEY,
 IpdAdmissionId INT NOT NULL,
 Category NVARCHAR(100) NOT NULL,
 FileName NVARCHAR(512) NOT NULL,
 StoredPath NVARCHAR(1024) NOT NULL,
 UploadedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 FOREIGN KEY(IpdAdmissionId) REFERENCES IpdAdmissions(Id)
);

CREATE TABLE OtBookings(
 Id INT IDENTITY PRIMARY KEY,
 BookingNumber NVARCHAR(100) NOT NULL UNIQUE,
 PatientId INT NULL,
 ExternalPatientName NVARCHAR(256) NULL,
 ExternalPatientPhone NVARCHAR(50) NULL,
 DoctorId INT NOT NULL,
 OtRoom NVARCHAR(20) NOT NULL,
 StartAtUtc DATETIME2 NOT NULL,
 EndAtUtc DATETIME2 NOT NULL,
 ProcedureName NVARCHAR(512) NULL,
 MedicinesUsed NVARCHAR(MAX) NULL,
 VitalsAndLabs NVARCHAR(MAX) NULL,
 Status NVARCHAR(50) NOT NULL DEFAULT 'Booked',
 FOREIGN KEY(PatientId) REFERENCES Patients(Id),
 FOREIGN KEY(DoctorId) REFERENCES Doctors(Id)
);
CREATE INDEX IX_OtBookings_Room_Time ON OtBookings(OtRoom,StartAtUtc,EndAtUtc);

CREATE TABLE Medicines(
 Id INT IDENTITY PRIMARY KEY,
 Name NVARCHAR(512) NOT NULL,
 ExpiryDate DATETIME2 NOT NULL,
 QuantityTablets INT NOT NULL,
 TabletsPerStrip INT NOT NULL DEFAULT 10,
 PricePerStrip DECIMAL(18,2) NOT NULL,
 BatchNumber NVARCHAR(100) NOT NULL,
 BoxNumber NVARCHAR(100),
 Section NVARCHAR(100),
 Component NVARCHAR(MAX),
 IsActive BIT NOT NULL DEFAULT 1
);
CREATE INDEX IX_Medicines_Search ON Medicines(Name,BatchNumber);

CREATE TABLE PharmacyBillReservations(
 Id INT IDENTITY PRIMARY KEY,
 BillId INT NOT NULL,
 MedicineId INT NOT NULL,
 QuantityTablets INT NOT NULL,
 StockReduced BIT NOT NULL DEFAULT 0,
 FOREIGN KEY(BillId) REFERENCES Bills(Id),
 FOREIGN KEY(MedicineId) REFERENCES Medicines(Id)
);

CREATE TABLE LabTests(
 Id INT IDENTITY PRIMARY KEY,
 Name NVARCHAR(512) NOT NULL,
 Price DECIMAL(18,2) NOT NULL,
 IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE LabTestComponents(
 Id INT IDENTITY PRIMARY KEY,
 LabTestId INT NOT NULL,
 Name NVARCHAR(512) NOT NULL,
 RangeText NVARCHAR(256),
 Unit NVARCHAR(100),
 DefaultValue NVARCHAR(256),
 FOREIGN KEY(LabTestId) REFERENCES LabTests(Id) ON DELETE CASCADE
);

CREATE TABLE LabOrders(
 Id INT IDENTITY PRIMARY KEY,
 OrderNumber NVARCHAR(100) NOT NULL UNIQUE,
 PatientId INT NOT NULL,
 IpdAdmissionId INT NULL,
 BillId INT NULL,
 CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 Status NVARCHAR(50) NOT NULL DEFAULT 'Ordered',
 FOREIGN KEY(PatientId) REFERENCES Patients(Id),
 FOREIGN KEY(IpdAdmissionId) REFERENCES IpdAdmissions(Id),
 FOREIGN KEY(BillId) REFERENCES Bills(Id)
);
CREATE INDEX IX_LabOrders_Patient_Date ON LabOrders(PatientId,CreatedAtUtc DESC);

CREATE TABLE LabOrderTests(
 Id INT IDENTITY PRIMARY KEY,
 LabOrderId INT NOT NULL,
 LabTestId INT NOT NULL,
 Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
 FOREIGN KEY(LabOrderId) REFERENCES LabOrders(Id) ON DELETE CASCADE,
 FOREIGN KEY(LabTestId) REFERENCES LabTests(Id)
);

CREATE TABLE LabResults(
 Id INT IDENTITY PRIMARY KEY,
 LabOrderTestId INT NOT NULL,
 LabTestComponentId INT NOT NULL,
 ComponentName NVARCHAR(512) NOT NULL,
 ResultValue NVARCHAR(256),
 RangeText NVARCHAR(256),
 Unit NVARCHAR(100),
 FOREIGN KEY(LabOrderTestId) REFERENCES LabOrderTests(Id) ON DELETE CASCADE,
 FOREIGN KEY(LabTestComponentId) REFERENCES LabTestComponents(Id)
);

CREATE TABLE AppSettings(
 Id INT IDENTITY PRIMARY KEY,
 [Key] NVARCHAR(256) NOT NULL UNIQUE,
 [Value] NVARCHAR(MAX) NOT NULL
);
GO
