<script setup>
import {ref,onMounted,computed} from 'vue';import {api} from '../api';import {can} from '../auth';
import Pagination from '../components/Pagination.vue';
import GridSearch from '../components/GridSearch.vue';
import { useGrid } from '../composables/useGrid';
const rows=ref([]),show=ref(false),form=ref({bedNumber:'',roomType:'Bed',cashRate:0,insuranceRate:0,ayushmanRate:0,isActive:true});
const pageSize=10;const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,pageSize);
async function load(){rows.value=(await api.get('/beds')).data}function add(){form.value={bedNumber:'',roomType:'Bed',cashRate:0,insuranceRate:0,ayushmanRate:0,isActive:true};show.value=true}function edit(x){form.value={...x};show.value=true}
async function save(){if(form.value.id)await api.put('/beds/'+form.value.id,form.value);else await api.post('/beds',form.value);show.value=false;load()}async function del(x){try{await api.delete('/beds/'+x.id);load()}catch(e){alert(e.response?.data?.message||'Unable to delete')}}
onMounted(load)
</script><template><h1>Bed / Cabin Master</h1><div class="toolbar"><button v-if="can('BED','add')" @click="add">+ Add Bed / Cabin</button></div><div class="grid-filter-row"><GridSearch v-model="search" placeholder="Search all bed/cabin fields..." /></div><table class="table"><tr><th class="sortable" @click="sortBy('bedNumber')">Number <span class="sort-indicator">{{sortIndicator('bedNumber')}}</span></th><th class="sortable" @click="sortBy('roomType')">Type <span class="sort-indicator">{{sortIndicator('roomType')}}</span></th><th class="sortable" @click="sortBy('cashRate')">Cash <span class="sort-indicator">{{sortIndicator('cashRate')}}</span></th><th class="sortable" @click="sortBy('insuranceRate')">Insurance <span class="sort-indicator">{{sortIndicator('insuranceRate')}}</span></th><th class="sortable" @click="sortBy('ayushmanRate')">Ayushman <span class="sort-indicator">{{sortIndicator('ayushmanRate')}}</span></th><th class="sortable" @click="sortBy('isOccupied')">Status <span class="sort-indicator">{{sortIndicator('isOccupied')}}</span></th><th></th></tr><tr v-for="x in pagedRows"><td>{{x.bedNumber}}</td><td>{{x.roomType}}</td><td>₹{{x.cashRate}}</td><td>₹{{x.insuranceRate}}</td><td>₹{{x.ayushmanRate}}</td><td>{{x.isOccupied?'Occupied':'Available'}}</td><td class="actions"><button v-if="can('BED','edit')" @click="edit(x)">Edit</button><button v-if="can('BED','delete')" class="danger-btn" @click="del(x)">Delete</button></td></tr></table><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="pageSize" @update:page="page=$event" />
<div v-if="show" class="modal-bg"><div class="modal"><button class="modal-close-x" @click="show = false">×</button><h2>Bed / Cabin</h2><div class="form-grid"><label>Number *<input v-model="form.bedNumber"></label><label>Type<select v-model="form.roomType"><option>Bed</option><option>Cabin</option><option>ICU</option></select></label><label>Cash Rate<input type="number" v-model.number="form.cashRate"></label><label>Insurance Rate<input type="number" v-model.number="form.insuranceRate"></label><label>Ayushman Rate<input type="number" v-model.number="form.ayushmanRate"></label></div><div class="modal-actions"><button @click="save">Save</button><button class="secondary" @click="show=false">Cancel</button></div></div></div></template>