<script setup>
import {computed,onMounted,ref} from 'vue';import {api} from '../api';import GridSearch from '../components/GridSearch.vue';import Pagination from '../components/Pagination.vue';import {useGrid} from '../composables/useGrid';
const today=new Date().toISOString().slice(0,10),from=ref(today),to=ref(today),rows=ref([]),staff=ref([]),show=ref(false),form=ref(blank());const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,10);const total=computed(()=>sortedRows.value.reduce((s,x)=>s+Number(x.amount||0),0));
function blank(){return{id:null,expenseDate:today,category:'General',description:'',amount:0,paymentMode:'Cash',paidByStaffId:null,referenceNumber:'',notes:''};}
async function load(){const [r,s]=await Promise.all([api.get('/expenses/daily',{params:{from:from.value,to:to.value}}),api.get('/staff')]);rows.value=r.data;staff.value=s.data;}
function add(){form.value=blank();show.value=true;}function edit(x){form.value={...x,expenseDate:String(x.expenseDate).slice(0,10)};show.value=true;}async function save(){if(!form.value.description.trim()||Number(form.value.amount)<=0){alert('Description and amount are required.');return;}if(form.value.id)await api.put(`/expenses/daily/${form.value.id}`,form.value);else await api.post('/expenses/daily',form.value);show.value=false;await load();}async function remove(x){if(confirm('Delete this expense?')){await api.delete(`/expenses/daily/${x.id}`);await load();}}onMounted(load);
</script>
<template><h1>Daily Expenses</h1><div class="toolbar"><label>From<input type="date" v-model="from"></label><label>To<input type="date" v-model="to"></label><button @click="load">Apply</button><button @click="add">+ Add Expense</button></div><GridSearch v-model="search" placeholder="Search category, description, payment mode, paid by staff, reference..." />
<table class="table"><tr><th class="sortable" @click="sortBy('expenseDate')">Date {{sortIndicator('expenseDate')}}</th><th>Category</th><th>Description</th><th>Mode</th><th>Paid By Staff</th><th>Reference</th><th>Amount</th><th></th></tr><tr v-for="x in pagedRows" :key="x.id"><td>{{String(x.expenseDate).slice(0,10)}}</td><td>{{x.category}}</td><td>{{x.description}}</td><td>{{x.paymentMode}}</td><td>{{x.paidByStaffName||'-'}}</td><td>{{x.referenceNumber||'-'}}</td><td>₹{{Number(x.amount).toFixed(2)}}</td><td class="actions"><button @click="edit(x)">Edit</button><button class="danger-btn" @click="remove(x)">Delete</button></td></tr></table><div class="bill-total-box"><div class="grand"><span>Total Expenses</span><b>₹{{total.toFixed(2)}}</b></div></div><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="10" @update:page="page=$event" />
<div v-if="show" class="modal-bg"><div class="modal"><button class="modal-close-x" @click="show = false">×</button><h2>{{form.id?'Edit':'Add'}} Daily Expense</h2><div class="form-grid"><label>Date *<input type="date" v-model="form.expenseDate"></label><label>Category<input v-model="form.category"></label><label class="full">Description *<input v-model="form.description"></label><label>Amount *<input type="number" min="0" step="0.01" v-model.number="form.amount"></label><label>Payment Mode<select v-model="form.paymentMode"><option>Cash</option><option>UPI</option><option>Card</option><option>Bank Transfer</option><option>Cheque</option><option>Other</option></select></label><label>Paid By Staff<select v-model.number="form.paidByStaffId"><option :value="null">Not specified</option><option v-for="x in staff" :key="x.id" :value="x.id">{{x.name}} · {{x.designation||'-'}}</option></select></label><label>Reference<input v-model="form.referenceNumber"></label><label class="full">Notes<textarea rows="3" v-model="form.notes"></textarea></label></div><div class="modal-actions"><button @click="save">Save</button><button class="secondary" @click="show=false">Cancel</button></div></div></div></template>