<script setup>
import {ref,onMounted,computed} from 'vue';import {api} from '../api';import {can} from '../auth';
import Pagination from '../components/Pagination.vue';
import GridSearch from '../components/GridSearch.vue';
import { useGrid } from '../composables/useGrid';
const rows=ref([]),show=ref(false),errors=ref([]),form=ref({name:'',specialisation:'',consultationCharge:0,ipdCharge:0,isActive:true});
const pageSize=10;const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,pageSize);
async function load(){rows.value=(await api.get('/doctors')).data}function add(){form.value={name:'',specialisation:'',consultationCharge:0,ipdCharge:0,isActive:true};errors.value=[];show.value=true}function edit(x){form.value={...x};errors.value=[];show.value=true}
async function save(){let e=[];if(!form.value.name.trim())e.push('Doctor name is required.');if(!form.value.specialisation.trim())e.push('Specialisation is required.');errors.value=e;if(e.length)return;try{if(form.value.id)await api.put('/doctors/'+form.value.id,form.value);else await api.post('/doctors',form.value);show.value=false;load()}catch(ex){errors.value=[ex.response?.data?.message||'Unable to save doctor.']}}
async function del(x){if(confirm('Disable this doctor?')){await api.delete('/doctors/'+x.id);load()}}onMounted(load)
</script><template><h1>Doctor Master</h1><div class="toolbar"><button v-if="can('DOCTOR','add')" @click="add">+ Add Doctor</button></div><div class="grid-filter-row"><GridSearch v-model="search" placeholder="Search all doctor fields..." /></div><table class="table"><tr><th class="sortable" @click="sortBy('name')">Name <span class="sort-indicator">{{sortIndicator('name')}}</span></th><th class="sortable" @click="sortBy('specialisation')">Specialisation <span class="sort-indicator">{{sortIndicator('specialisation')}}</span></th><th class="sortable" @click="sortBy('consultationCharge')">OPD Charge <span class="sort-indicator">{{sortIndicator('consultationCharge')}}</span></th><th class="sortable" @click="sortBy('ipdCharge')">IPD Charge <span class="sort-indicator">{{sortIndicator('ipdCharge')}}</span></th><th class="sortable" @click="sortBy('isActive')">Status <span class="sort-indicator">{{sortIndicator('isActive')}}</span></th><th></th></tr><tr v-for="x in pagedRows"><td>{{x.name}}</td><td>{{x.specialisation}}</td><td>₹{{x.consultationCharge}}</td><td>₹{{x.ipdCharge}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td class="actions"><button v-if="can('DOCTOR','edit')" @click="edit(x)">Edit</button><button v-if="can('DOCTOR','delete')" class="danger-btn" @click="del(x)">Delete</button></td></tr></table><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="pageSize" @update:page="page=$event" />
<div v-if="show" class="modal-bg"><div class="modal"><button class="modal-close-x" @click="show=false">×</button><h2>{{form.id?'Edit':'Add'}} Doctor</h2><div v-if="errors.length" class="error-box"><div v-for="e in errors">{{e}}</div></div><div class="form-grid"><label>Name *<input v-model="form.name"></label><label>OPD Consultation Charge *<input type="number" min="0" v-model.number="form.consultationCharge"></label><label>IPD Charge *<input type="number" min="0" v-model.number="form.ipdCharge"></label><label class="full">Specialisation *<textarea rows="4" v-model="form.specialisation"></textarea></label></div><div class="modal-actions"><button @click="save">Save</button><button class="secondary" @click="show=false">Cancel</button></div></div></div></template>