<script setup>
import {computed,onMounted,ref} from 'vue';import {api} from '../api';import GridSearch from '../components/GridSearch.vue';import Pagination from '../components/Pagination.vue';import {useGrid} from '../composables/useGrid';
const today=new Date(),from=ref(new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10)),to=ref(today.toISOString().slice(0,10)),doctorId=ref(null),sourceType=ref('All'),rows=ref([]),summary=ref({}),doctors=ref([]),staff=ref([]),payment=ref(null);const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,10);
async function load(){const [r,d,s]=await Promise.all([api.get('/doctor-settlements',{params:{from:from.value,to:to.value,doctorId:doctorId.value||undefined,sourceType:sourceType.value}}),api.get('/doctors'),api.get('/staff')]);rows.value=r.data.rows||[];summary.value=r.data;doctors.value=d.data;staff.value=s.data;}
function openPayment(x){payment.value={id:x.id,doctorName:x.doctorName,payableAmount:x.payableAmount,paidAmount:x.paidAmount||0,paymentDate:x.paymentDate?String(x.paymentDate).slice(0,10):to.value,paymentMode:x.paymentMode||'Cash',referenceNumber:x.referenceNumber||'',notes:x.notes||'',paidByStaffId:x.paidByStaffId||null};}
async function save(){await api.post(`/doctor-settlements/${payment.value.id}/payment`,payment.value);payment.value=null;await load();}onMounted(load);
</script>
<template><h1>Doctor Settlement</h1><div class="toolbar"><label>From<input type="date" v-model="from"></label><label>To<input type="date" v-model="to"></label><label>Doctor<select v-model.number="doctorId"><option :value="null">All Doctors</option><option v-for="d in doctors" :key="d.id" :value="d.id">{{d.name}}</option></select></label><label>Type<select v-model="sourceType"><option>All</option><option>Consultation</option><option>OT</option></select></label><button @click="load">Apply</button></div><GridSearch v-model="search" placeholder="Search doctor, consultation, OT, amount, payment mode..." />
<div class="grid"><div class="card"><div class="muted">Doctor Payable</div><div class="metric">₹{{Number(summary.totalPayable||0).toFixed(2)}}</div></div><div class="card"><div class="muted">Paid</div><div class="metric">₹{{Number(summary.totalPaid||0).toFixed(2)}}</div></div><div class="card"><div class="muted">Outstanding</div><div class="metric">₹{{Number(summary.totalOutstanding||0).toFixed(2)}}</div></div></div>
<table class="table"><tr><th class="sortable" @click="sortBy('earnedDate')">Date {{sortIndicator('earnedDate')}}</th><th>Doctor</th><th>Type</th><th>Description</th><th>Payable</th><th>Paid</th><th>Outstanding</th><th>Payment</th><th></th></tr><tr v-for="x in pagedRows" :key="x.id"><td>{{String(x.earnedDate).slice(0,10)}}</td><td><b>{{x.doctorName}}</b></td><td>{{x.sourceType}}</td><td>{{x.description}}</td><td>₹{{Number(x.payableAmount).toFixed(2)}}</td><td>₹{{Number(x.paidAmount).toFixed(2)}}</td><td><b>₹{{Number(x.outstanding).toFixed(2)}}</b></td><td>{{x.paymentMode||'-'}}<div class="muted">{{x.paymentDate?String(x.paymentDate).slice(0,10):''}}</div></td><td><button @click="openPayment(x)">Manage Payment</button></td></tr></table><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="10" @update:page="page=$event" />
<div v-if="payment" class="modal-bg"><div class="modal"><button class="modal-close-x" @click="payment = null">×</button><h2>Doctor Payment · {{payment.doctorName}}</h2><div class="card"><b>Payable: ₹{{Number(payment.payableAmount).toFixed(2)}}</b></div><div class="form-grid" style="margin-top:14px"><label>Paid Amount<input type="number" min="0" :max="payment.payableAmount" step="0.01" v-model.number="payment.paidAmount"></label><label>Payment Date<input type="date" v-model="payment.paymentDate"></label><label>Mode<select v-model="payment.paymentMode"><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Cheque</option><option>Other</option></select></label><label>Paid By Staff<select v-model.number="payment.paidByStaffId"><option :value="null">Not specified</option><option v-for="x in staff" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label>Reference<input v-model="payment.referenceNumber"></label><label class="full">Notes<textarea rows="3" v-model="payment.notes"></textarea></label></div><div class="modal-actions"><button @click="save">Save Payment</button><button class="secondary" @click="payment=null">Cancel</button></div></div></div></template>
