<script setup>
import {ref,onMounted,computed} from 'vue';import {api} from '../api';import {can} from '../auth';
import Pagination from '../components/Pagination.vue';
import GridSearch from '../components/GridSearch.vue';
import { useGrid } from '../composables/useGrid';
const rows=ref([]),detail=ref(null),show=ref(false),mode=ref('detail'),doctors=ref([]),tests=ref([]),settings=ref([]),discounts=ref([]),vital=ref({}),doctorNote=ref({doctorId:null,suggestion:''}),nursing=ref({actionTaken:''});
const pageSize=10;const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,pageSize);
const lab=ref({tests:[{labTestId:null,discountTypeId:null}]});const bill=ref({bulkDiscountTypeId:null,roundOff:0,items:[{description:'',quantity:1,unitPrice:0,discountTypeId:null}]});
async function load(){const [r,d,t,st,di]=await Promise.all([api.get('/ipd'),api.get('/doctors'),api.get('/lab/tests'),api.get('/settings'),api.get('/discounts',{params:{activeOnly:true}})]);rows.value=r.data;doctors.value=d.data;tests.value=t.data;settings.value=st.data;discounts.value=di.data}
async function open(x,m='detail'){mode.value=m;detail.value=(await api.get(`/ipd/${x.id}/detail`)).data;doctorNote.value={doctorId:detail.value.admission.doctorId,suggestion:''};prefillBill();show.value=true}
async function refresh(){detail.value=(await api.get(`/ipd/${detail.value.admission.id}/detail`)).data}
function rate(){const b=detail.value.bed;return detail.value.admission.payerType==='Insurance'?b.insuranceRate:detail.value.admission.payerType==='Ayushman'?b.ayushmanRate:b.cashRate}
function prefillBill(){bill.value={bulkDiscountTypeId:null,roundOff:0,items:[{description:`${detail.value.bed.roomType} Charge - ${detail.value.bed.bedNumber}`,quantity:1,unitPrice:rate(),discountTypeId:null},{description:`Doctor Visit - ${detail.value.doctor.name}`,quantity:1,unitPrice:detail.value.doctor.ipdCharge,discountTypeId:null}]}}
function addBillItem(){bill.value.items.push({description:'',quantity:1,unitPrice:0,discountTypeId:null})}
function billItemRaw(i){return Number(i.quantity||0)*Number(i.unitPrice||0)}
function billItemDiscount(i){return discountAmt(billItemRaw(i),i.discountTypeId)}
function billBeforeDiscount(){return bill.value.items.reduce((t,i)=>t+billItemRaw(i),0)}
function billIndividualDiscount(){return bill.value.items.reduce((t,i)=>t+billItemDiscount(i),0)}
function billAfterIndividual(){return billBeforeDiscount()-billIndividualDiscount()}
function billBulkDiscount(){return discountAmt(billAfterIndividual(),bill.value.bulkDiscountTypeId,'Bulk')}
function billAfterDiscount(){return billAfterIndividual()-billBulkDiscount()}
// Small manual nudge (-9..9) folded into the bill total, e.g. 448 -> 450; never a separate print line.
function billFinalAmount(){return billAfterDiscount()+Number(bill.value.roundOff||0)}
async function createIpdBill(){if(bill.value.roundOff<-9||bill.value.roundOff>9){alert('Round off must be between -9 and 9.');return}await api.post('/bills',{patientId:detail.value.patient.id,doctorId:detail.value.admission.doctorId,billType:'IPD',...bill.value});prefillBill();refresh();alert('IPD bill created.')}
async function saveVital(){await api.post(`/ipd/${detail.value.admission.id}/vitals`,vital.value);vital.value={};refresh()}
async function saveDoctor(){await api.post(`/ipd/${detail.value.admission.id}/doctor-note`,doctorNote.value);doctorNote.value={doctorId:detail.value.admission.doctorId,suggestion:''};refresh()}
async function saveNursing(){await api.post(`/ipd/${detail.value.admission.id}/nursing-note`,nursing.value);nursing.value={actionTaken:''};refresh()}
function addLabLine(){lab.value.tests.push({labTestId:null,discountTypeId:null})}
function removeLabLine(i){lab.value.tests.splice(i,1)}
function labObj(l){return tests.value.find(t=>t.id===l.labTestId)}
function labPrice(l){return Number(labObj(l)?.price||0)}
function discountAmt(amount,id,scope='Individual'){const d=discounts.value.find(x=>x.id===id&&x.scope===scope&&x.isActive);if(!d)return 0;return d.discountMode==='Amount'?Math.min(amount,Number(d.value||0)):amount*Math.min(100,Math.max(0,Number(d.value||0)))/100}function labDisc(l){return discountAmt(labPrice(l),l.discountTypeId)}
async function createLab(){if(!lab.value.tests.length||lab.value.tests.some(x=>!x.labTestId)){alert('Select a test for every row.');return}await api.post('/lab/orders',{patientId:detail.value.patient.id,ipdAdmissionId:detail.value.admission.id,tests:lab.value.tests});lab.value={tests:[{labTestId:null,discountTypeId:null}]};refresh();alert('Lab order and bill created.')}
onMounted(load)
</script><template><h1>IPD</h1><div class="grid-filter-row"><GridSearch v-model="search" placeholder="Search all IPD fields..." /></div><table class="table"><tr><th class="sortable" @click="sortBy('admissionNumber')">Admission <span class="sort-indicator">{{sortIndicator('admissionNumber')}}</span></th><th class="sortable" @click="sortBy('patientName')">Patient <span class="sort-indicator">{{sortIndicator('patientName')}}</span></th><th class="sortable" @click="sortBy('doctorName')">Doctor <span class="sort-indicator">{{sortIndicator('doctorName')}}</span></th><th class="sortable" @click="sortBy('bedNumber')">Bed/Cabin <span class="sort-indicator">{{sortIndicator('bedNumber')}}</span></th><th class="sortable" @click="sortBy('payerType')">Payer <span class="sort-indicator">{{sortIndicator('payerType')}}</span></th><th class="sortable" @click="sortBy('admittedAtUtc')">Admitted <span class="sort-indicator">{{sortIndicator('admittedAtUtc')}}</span></th><th></th></tr><tr v-for="x in pagedRows"><td>{{x.admissionNumber}}</td><td>{{x.patientName}}</td><td>{{x.doctorName}}</td><td>{{x.bedNumber}}</td><td>{{x.payerType}}</td><td>{{new Date(x.admittedAtUtc).toLocaleString()}}</td><td class="actions"><button @click="open(x,'detail')">IPD Details</button><button @click="open(x,'bill')">Add Bill</button><button @click="open(x,'lab')">Add Lab</button><button @click="location.href='/pharmacy/sales?patientId='+x.patientId">Add Pharmacy</button></td></tr></table><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="pageSize" @update:page="page=$event" />
<div v-if="show" class="modal-bg"><div class="modal modal-xl"><button class="modal-close-x" @click="show=false">×</button><div class="page-head"><div><h2>{{detail.patient.name}} · {{detail.admission.admissionNumber}}</h2><div class="muted">{{detail.doctor.name}} · {{detail.bed.bedNumber}} · {{detail.admission.payerType}}</div></div><button class="secondary" @click="show=false">Close</button></div>
<div v-if="mode==='detail'" class="ipd-columns"><section class="card"><h3>Add Vital</h3><div class="form-grid"><label>BP<input v-model="vital.bloodPressure"></label><label>Temperature °F<input type="number" v-model.number="vital.temperatureC"></label><label>Pulse<input type="number" v-model.number="vital.pulse"></label><label>SpO₂<input type="number" v-model.number="vital.spo2"></label><label class="full">Notes<textarea v-model="vital.notes"></textarea></label></div><button @click="saveVital">Save Vital</button></section>
<section class="card"><h3>Doctor Suggestion</h3><select v-model.number="doctorNote.doctorId"><option v-for="d in doctors.filter(x=>x.isActive)" :value="d.id">{{d.name}}</option></select><textarea rows="5" v-model="doctorNote.suggestion"></textarea><button @click="saveDoctor">Save Suggestion</button></section>
<section class="card"><h3>Nursing Activity</h3><textarea rows="7" v-model="nursing.actionTaken"></textarea><button @click="saveNursing">Save Activity</button></section></div>
<div v-if="mode==='detail'"><h3>Vitals History</h3><table class="table"><tr><th>Time</th><th>BP</th><th>Temp (°F)</th><th>Pulse</th><th>SpO₂</th><th>Notes</th></tr><tr v-for="x in detail.vitals"><td>{{new Date(x.recordedAtUtc).toLocaleString()}}</td><td>{{x.bloodPressure}}</td><td>{{x.temperatureC}}</td><td>{{x.pulse}}</td><td>{{x.spo2}}</td><td>{{x.notes}}</td></tr></table>
<h3>Doctor Suggestions</h3><table class="table"><tr><th>Time</th><th>Doctor</th><th>Suggestion</th></tr><tr v-for="x in detail.doctorNotes"><td>{{new Date(x.createdAtUtc).toLocaleString()}}</td><td>{{x.doctorName}}</td><td>{{x.suggestion}}</td></tr></table>
<h3>Nursing Activity</h3><table class="table"><tr><th>Time</th><th>Action</th></tr><tr v-for="x in detail.nursingNotes"><td>{{new Date(x.createdAtUtc).toLocaleString()}}</td><td>{{x.actionTaken}}</td></tr></table>
</div><div v-if="mode==='bill'" class="card" style="margin-top:22px"><h3>Create IPD Bill</h3><div class="muted">Create multiple bills during the admission for bed/cabin, doctor visits, nursing, oxygen, medicines, instruments or any custom charge.</div><table class="table"><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Discount</th></tr><tr v-for="i in bill.items"><td><input v-model="i.description"></td><td><input type="number" v-model.number="i.quantity"></td><td><input type="number" v-model.number="i.unitPrice"></td><td><select v-model.number="i.discountTypeId"><option :value="null">No Discount</option><option v-for="d in discounts.filter(x=>x.scope==='Individual'&&x.isActive)" :key="d.id" :value="d.id">{{d.name}} · {{d.discountMode==='Percent'?d.value+'%':'₹'+Number(d.value).toFixed(2)}}</option></select></td></tr></table><label>Bulk Discount<select v-model.number="bill.bulkDiscountTypeId"><option :value="null">No Bulk Discount</option><option v-for="d in discounts.filter(x=>x.scope==='Bulk'&&x.isActive)" :key="d.id" :value="d.id">{{d.name}} · {{d.discountMode==='Percent'?d.value+'%':'₹'+Number(d.value).toFixed(2)}}</option></select></label><div class="bill-total-box"><div><span>Before Discount</span><b>₹{{billBeforeDiscount().toFixed(2)}}</b></div><div class="grand"><span>After Discount</span><b>₹{{billAfterDiscount().toFixed(2)}}</b></div><div><span>Round Off (-9 to 9)</span><input v-model.number="bill.roundOff" type="number" min="-9" max="9" step="1" style="width:80px;display:inline-block"></div><div class="grand"><span>Final Amount</span><b>₹{{billFinalAmount().toFixed(2)}}</b></div></div><div class="toolbar"><button @click="addBillItem">+ Item</button><button @click="createIpdBill">Create IPD Bill</button></div></div>
<h3>IPD Bills</h3><table class="table"><tr><th>Bill</th><th>Net</th><th>Paid</th><th>Status</th></tr><tr v-for="b in detail.bills"><td>{{b.billNumber}}</td><td>₹{{b.netAmount}}</td><td>₹{{b.paidAmount}}</td><td>{{b.status}}</td></tr></table>
<div v-if="mode==='lab'" class="card ipd-lab"><h3>Add Lab Tests</h3><table class="table"><tr><th>Test</th><th>Price</th><th>Approved Discount</th><th>Discount</th><th>Net</th><th></th></tr><tr v-for="(l,i) in lab.tests"><td><select v-model.number="l.labTestId"><option :value="null">Select Test</option><option v-for="t in tests" :value="t.id">{{t.name}}</option></select></td><td>₹{{labPrice(l).toFixed(2)}}</td><td><select v-model.number="l.discountTypeId"><option :value="null">No Discount</option><option v-for="d in discounts.filter(x=>x.scope==='Individual'&&x.isActive)" :key="d.id" :value="d.id">{{d.name}} · {{d.discountMode==='Percent'?d.value+'%':'₹'+Number(d.value).toFixed(2)}}</option></select></td><td>₹{{labDisc(l).toFixed(2)}}</td><td>₹{{(labPrice(l)-labDisc(l)).toFixed(2)}}</td><td><button class="danger-btn" @click="removeLabLine(i)">×</button></td></tr></table><div class="toolbar"><button @click="addLabLine">+ Add Test</button><button @click="createLab">Create Lab Order + Bill</button></div><h4>Lab Orders for this admission</h4><table class="table"><tr><th>Order</th><th>Date</th><th>Status</th></tr><tr v-for="o in detail.labOrders"><td>{{o.orderNumber}}</td><td>{{new Date(o.createdAtUtc).toLocaleString()}}</td><td>{{o.status}}</td></tr></table></div>
<div class="modal-actions"><button class="secondary" @click="show=false">Close</button></div></div></div></template>