<script setup>
import {ref,onMounted,computed} from 'vue';import {api,assetUrl} from '../api';import {can} from '../auth';import Pagination from '../components/Pagination.vue';
const tests=ref([]),orders=ref([]),patients=ref([]),testPage=ref(1),orderPage=ref(1),showMaster=ref(false),showOrder=ref(false),showTests=ref(false),showResult=ref(false),selectedOrder=ref(null),orderTests=ref([]),resultData=ref(null),errors=ref([]);
const pageSize=10;const testPageCount=computed(()=>Math.max(1,Math.ceil(tests.value.length/pageSize)));const orderPageCount=computed(()=>Math.max(1,Math.ceil(orders.value.length/pageSize)));const pagedTests=computed(()=>tests.value.slice((testPage.value-1)*pageSize,testPage.value*pageSize));const pagedOrders=computed(()=>orders.value.slice((orderPage.value-1)*pageSize,orderPage.value*pageSize));
const master=ref({name:'',price:0,note:'',components:[{name:'',rangeText:'',unit:'',defaultValue:''}]});
const order=ref({patientId:null,tests:[{labTestId:null,discountMode:'Percent',discountValue:0}]});
async function load(){tests.value=(await api.get('/lab/tests')).data;orders.value=(await api.get('/lab/orders')).data;patients.value=(await api.get('/patients')).data}
function newMaster(){master.value={name:'',price:0,note:'',components:[{name:'',rangeText:'',unit:'',defaultValue:''}]};showMaster.value=true}function editMaster(x){master.value=JSON.parse(JSON.stringify(x));showMaster.value=true}
function addComp(){master.value.components.push({name:'',rangeText:'',unit:'',defaultValue:''})}function removeComp(i){master.value.components.splice(i,1)}
async function saveMaster(){if(!master.value.name.trim()){errors.value=['Test name is required.'];return}if(master.value.id)await api.put('/lab/tests/'+master.value.id,master.value);else await api.post('/lab/tests',master.value);showMaster.value=false;load()}
function newOrder(){order.value={patientId:null,tests:[{labTestId:null,discountMode:'Percent',discountValue:0}]};showOrder.value=true}function addTestLine(){order.value.tests.push({labTestId:null,discountMode:'Percent',discountValue:0})}function removeTestLine(i){order.value.tests.splice(i,1)}
function testObj(l){return tests.value.find(t=>t.id===l.labTestId)}function linePrice(l){return Number(testObj(l)?.price||0)}function lineDisc(l){const p=linePrice(l);return l.discountMode==='Amount'?Math.min(p,Number(l.discountValue||0)):p*Math.min(100,Math.max(0,Number(l.discountValue||0)))/100}function beforeTotal(){return order.value.tests.reduce((a,l)=>a+linePrice(l),0)}function afterTotal(){return order.value.tests.reduce((a,l)=>a+linePrice(l)-lineDisc(l),0)}
async function saveOrder(){if(!order.value.patientId||order.value.tests.some(x=>!x.labTestId)){alert('Select patient and test for every row.');return}await api.post('/lab/orders',order.value);showOrder.value=false;load()}
async function openOrder(x){selectedOrder.value=x;orderTests.value=(await api.get(`/lab/orders/${x.id}/tests`)).data;showTests.value=true}async function openResult(t){resultData.value=(await api.get(`/lab/order-tests/${t.id}`)).data;showResult.value=true}
async function saveResults(){await api.put(`/lab/order-tests/${resultData.value.orderTestId}/results`,{results:resultData.value.results.map(x=>({labResultId:x.id,resultValue:x.resultValue}))});showResult.value=false;openOrder(selectedOrder.value);load()}
function printLabHtml(html){const iframe=document.createElement('iframe');iframe.style.position='fixed';iframe.style.width='0';iframe.style.height='0';iframe.style.border='0';document.body.appendChild(iframe);const doc=iframe.contentWindow.document;doc.open();doc.write(html);doc.close();iframe.onload=()=>{iframe.contentWindow.focus();iframe.contentWindow.print();iframe.contentWindow.onafterprint=()=>iframe.remove();setTimeout(()=>{if(document.body.contains(iframe))iframe.remove()},60000)}}
async function printResult(t){const {data}=await api.get(`/lab/order-tests/${t.id}/print`);const rows=data.results.map(r=>`<tr><td>${r.componentName}</td><td>${r.resultValue??''}</td><td>${r.rangeText??''}</td><td>${r.unit??''}</td></tr>`).join('');printLabHtml(`<!doctype html><html><head><title></title><style>@page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;width:210mm;font-family:Arial}.header img{display:block;width:210mm;height:34mm;object-fit:fill}.content{padding:8mm 12mm 12mm}.patient{margin:0 0 14px;padding:10px;border:1px solid #333;display:grid;grid-template-columns:1fr 1fr;gap:6px 16px;font-size:13px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #333;padding:8px}.note{margin-top:16px;font-size:12px}</style></head><body><div class="header">${data.hospital.labHeader?`<img src="${assetUrl(data.hospital.labHeader)}">`:''}</div><div class="content"><div class="patient"><div><b>Patient:</b> ${data.patient.name}</div><div><b>ID:</b> ${data.patient.patientCode}</div><div><b>Age / Gender:</b> ${data.patient.age} / ${data.patient.gender}</div><div><b>Phone:</b> ${data.patient.phone}</div></div><h3>${data.test.name}</h3><table><tr><th>Component</th><th>Result</th><th>Range</th><th>Unit</th></tr>${rows}</table><Pagination :page="orderPage" :page-count="orderPageCount" :total="orders.length" :page-size="pageSize" @update:page="orderPage=$event" /><Pagination :page="testPage" :page-count="testPageCount" :total="tests.length" :page-size="pageSize" @update:page="testPage=$event" />${data.test.note?`<div class="note"><b>Note:</b> ${data.test.note}</div>`:''}</div></body></html>`)}
onMounted(load)
</script>
<template><h1>Lab</h1><div class="toolbar"><button v-if="can('LAB','add')" @click="newMaster">+ Add Test Master</button><button @click="newOrder">+ Add Tests for Patient</button></div>
<h2>Lab Test Master</h2><table class="table"><tr><th>Test</th><th>Price</th><th>Components</th><th>Note</th><th></th></tr><tr v-for="x in pagedTests"><td>{{x.name}}</td><td>₹{{x.price}}</td><td><span v-for="c in x.components" class="pill">{{c.name}} · {{c.rangeText}} {{c.unit}}</span></td><td>{{x.note}}</td><td><button v-if="can('LAB','edit')" @click="editMaster(x)">Edit</button></td></tr></table>
<h2 style="margin-top:28px">Patient Lab Orders & Results</h2><table class="table"><tr><th>Order</th><th>Patient</th><th>Date</th><th>Tests</th><th>Status</th><th></th></tr><tr v-for="x in pagedOrders"><td>{{x.orderNumber}}</td><td>{{x.patientName}}<div class="muted">{{x.patientCode}}</div></td><td>{{new Date(x.createdAtUtc).toLocaleString()}}</td><td>{{x.testCount}}</td><td>{{x.status}}</td><td><button @click="openOrder(x)">View / Update Results</button></td></tr></table>
<div v-if="showMaster" class="modal-bg"><div class="modal modal-xl"><h2>Lab Test Master</h2><div class="form-grid"><label>Test Name *<input v-model="master.name"></label><label>Price *<input type="number" v-model.number="master.price"></label></div><table class="table" style="margin-top:15px"><tr><th>Component *</th><th>Range</th><th>Unit</th><th>Prefilled Value</th><th></th></tr><tr v-for="(c,i) in master.components"><td><input v-model="c.name"></td><td><input v-model="c.rangeText"></td><td><input v-model="c.unit"></td><td><input v-model="c.defaultValue"></td><td><button class="danger-btn" @click="removeComp(i)">×</button></td></tr></table><button @click="addComp">+ Component</button><label style="display:block;margin-top:18px">Note<textarea rows="4" v-model="master.note"></textarea></label><div class="modal-actions"><button @click="saveMaster">Save</button><button class="secondary" @click="showMaster=false">Cancel</button></div></div></div>
<div v-if="showOrder" class="modal-bg"><div class="modal modal-xl"><h2>Add Tests for Patient</h2><label>Patient *<select v-model.number="order.patientId"><option :value="null">Select Patient</option><option v-for="p in patients" :value="p.id">{{p.name}} · {{p.patientCode}}</option></select></label><table class="table" style="margin-top:16px"><tr><th>Test</th><th>Price</th><th>Discount Type</th><th>Discount</th><th>After Discount</th><th></th></tr><tr v-for="(l,i) in order.tests"><td><select v-model.number="l.labTestId"><option :value="null">Select Test</option><option v-for="t in tests" :value="t.id">{{t.name}}</option></select></td><td>₹{{linePrice(l).toFixed(2)}}</td><td><select v-model="l.discountMode"><option>Percent</option><option>Amount</option></select></td><td><input type="number" v-model.number="l.discountValue"></td><td>₹{{(linePrice(l)-lineDisc(l)).toFixed(2)}}</td><td><button class="danger-btn" @click="removeTestLine(i)">×</button></td></tr></table><button @click="addTestLine">+ Add Test</button><div class="bill-total-box"><div><span>Before Discount</span><b>₹{{beforeTotal().toFixed(2)}}</b></div><div class="grand"><span>After Discount</span><b>₹{{afterTotal().toFixed(2)}}</b></div></div><div class="muted">A bill is created automatically for all selected tests.</div><div class="modal-actions"><button @click="saveOrder">Create Tests + Bill</button><button class="secondary" @click="showOrder=false">Cancel</button></div></div></div>
<div v-if="showTests" class="modal-bg"><div class="modal modal-lg"><h2>{{selectedOrder.patientName}} · {{selectedOrder.orderNumber}}</h2><table class="table"><tr><th>Test</th><th>Price</th><th>Discount</th><th>Net</th><th>Status</th><th></th></tr><tr v-for="t in orderTests"><td>{{t.testName}}</td><td>₹{{t.unitPrice}}</td><td>₹{{t.discountAmount}}</td><td>₹{{t.netAmount}}</td><td>{{t.status}}</td><td class="actions"><button @click="openResult(t)">View / Edit Result</button><button @click="printResult(t)">Print Result</button></td></tr></table><div class="modal-actions"><button class="secondary" @click="showTests=false">Close</button></div></div></div>
<div v-if="showResult" class="modal-bg"><div class="modal modal-xl"><h2>{{resultData.testName}} · {{resultData.patient?.name}}</h2><table class="table"><tr><th>Component</th><th>Result</th><th>Range</th><th>Unit</th></tr><tr v-for="r in resultData.results"><td>{{r.componentName}}</td><td><input v-model="r.resultValue"></td><td>{{r.rangeText}}</td><td>{{r.unit}}</td></tr></table><div class="modal-actions"><button @click="saveResults">Save Results</button><button class="secondary" @click="showResult=false">Cancel</button></div></div></div>
</template>