<script setup>
import { computed, onMounted, ref } from 'vue';
import { api } from '../api';
import GridSearch from '../components/GridSearch.vue';
import Pagination from '../components/Pagination.vue';
import { useGrid } from '../composables/useGrid';
const today=new Date().toISOString().slice(0,10); const rows=ref([]); const staff=ref([]); const show=ref(false); const form=ref(blank());
const {search,page,pageCount,pagedRows,sortedRows}=useGrid(rows,10); const total=computed(()=>rows.value.reduce((s,x)=>s+Number(x.amount||0),0));
function blank(){return{id:null,expenseDate:today,vendorName:'',invoiceNumber:'',description:'',amount:0,paidAmount:0,paymentDate:today,paymentMode:'Cash',referenceNumber:'',notes:'',paidByStaffId:null};}
async function load(){const [r,s]=await Promise.all([api.get('/expenses/lab'),api.get('/staff')]);rows.value=r.data;staff.value=s.data;} function add(){form.value=blank();show.value=true;} function edit(row){form.value={...row,expenseDate:String(row.expenseDate).slice(0,10),paymentDate:row.paymentDate?String(row.paymentDate).slice(0,10):null};show.value=true;}
async function save(){if(form.value.id)await api.put(`/expenses/lab/${form.value.id}`,form.value);else await api.post('/expenses/lab',form.value);show.value=false;await load();} async function remove(row){if(confirm('Delete this lab purchase?')){await api.delete(`/expenses/lab/${row.id}`);await load();}}
onMounted(load);
</script>
<template><h1>Lab Expenses</h1><div class="toolbar"><button @click="add">+ Add Lab Purchase</button></div><GridSearch v-model="search" placeholder="Search vendor, invoice, item, amount, payment..."/><table class="table"><tr><th>Date</th><th>Vendor</th><th>Invoice</th><th>Description</th><th>Amount</th><th>Paid</th><th>Paid By</th><th>Outstanding</th><th></th></tr><tr v-for="row in pagedRows" :key="row.id"><td>{{String(row.expenseDate).slice(0,10)}}</td><td>{{row.vendorName||'-'}}</td><td>{{row.invoiceNumber||'-'}}</td><td>{{row.description}}</td><td>₹{{Number(row.amount).toFixed(2)}}</td><td>₹{{Number(row.paidAmount).toFixed(2)}}</td><td>{{row.paidByStaffName||'-'}}</td><td>₹{{Math.max(0,Number(row.amount)-Number(row.paidAmount)).toFixed(2)}}</td><td class="actions"><button @click="edit(row)">Edit</button><button class="danger-btn" @click="remove(row)">Delete</button></td></tr></table><div class="bill-total-box"><div class="grand"><span>Total Lab Purchases</span><b>₹{{total.toFixed(2)}}</b></div></div><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="10" @update:page="page=$event"/>
<div v-if="show" class="modal-bg"><div class="modal modal-lg"><button class="modal-close-x" @click="show=false">×</button><h2>{{form.id?'Edit':'Add'}} Lab Purchase</h2><div class="form-grid"><label>Date<input type="date" v-model="form.expenseDate"></label><label>Vendor<input v-model="form.vendorName"></label><label>Invoice No<input v-model="form.invoiceNumber"></label><label class="full">Item / Description *<input v-model="form.description"></label><label>Amount *<input type="number" min="0" step="0.01" v-model.number="form.amount"></label><label>Paid Amount<input type="number" min="0" :max="form.amount" step="0.01" v-model.number="form.paidAmount"></label><label>Payment Date<input type="date" v-model="form.paymentDate"></label><label>Mode<select v-model="form.paymentMode"><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Cheque</option><option>Credit</option><option>Other</option></select></label><label>Paid By Staff<select v-model.number="form.paidByStaffId"><option :value="null">Not specified</option><option v-for="x in staff" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label>Reference<input v-model="form.referenceNumber"></label><label class="full">Notes<textarea rows="3" v-model="form.notes"></textarea></label></div><div class="modal-actions"><button @click="save">Save</button><button class="secondary" @click="show=false">Cancel</button></div></div></div></template>
