<script setup>
import { onMounted, ref } from 'vue';import { api } from '../api';import GridSearch from '../components/GridSearch.vue';import Pagination from '../components/Pagination.vue';import {useGrid} from '../composables/useGrid';
const rows=ref([]),designations=ref([]),show=ref(false),form=ref(blank());const {search,page,pageCount,pagedRows,sortedRows,sortBy,sortIndicator}=useGrid(rows,10);
function blank(){return{id:null,name:'',designationId:null,dateOfBirth:null,phone:'',address:'',accountNumber:'',monthlySalary:0,dateOfJoining:new Date().toISOString().slice(0,10),isActive:true};}
async function load(){const [s,d]=await Promise.all([api.get('/staff',{params:{includeInactive:true}}),api.get('/staff-designations')]);rows.value=s.data;designations.value=d.data;}
function add(){form.value=blank();show.value=true;} function edit(x){form.value={...x,dateOfBirth:x.dateOfBirth?String(x.dateOfBirth).slice(0,10):null,dateOfJoining:x.dateOfJoining?String(x.dateOfJoining).slice(0,10):null};show.value=true;}
async function save(){if(!form.value.name.trim()){alert('Staff name is required.');return;}if(!form.value.designationId){alert('Designation is required.');return;}if(form.value.id)await api.put(`/staff/${form.value.id}`,form.value);else await api.post('/staff',form.value);show.value=false;await load();}
async function remove(x){if(!confirm(`Deactivate ${x.name}?`))return;await api.delete(`/staff/${x.id}`);await load();}onMounted(load);
</script>
<template><h1>Staff Master</h1><div class="toolbar"><button @click="add">+ Add Staff</button></div><GridSearch v-model="search" placeholder="Search staff code, name, designation, phone, address, salary..." />
<table class="table"><tr><th class="sortable" @click="sortBy('staffCode')">Staff ID {{sortIndicator('staffCode')}}</th><th class="sortable" @click="sortBy('name')">Name {{sortIndicator('name')}}</th><th>Designation</th><th>DOB</th><th>Phone</th><th>Account Number</th><th>Address</th><th>Salary</th><th>Status</th><th></th></tr>
<tr v-for="x in pagedRows" :key="x.id"><td>{{x.staffCode}}</td><td><b>{{x.name}}</b></td><td>{{x.designation||'-'}}</td><td>{{x.dateOfBirth?String(x.dateOfBirth).slice(0,10):'-'}}</td><td>{{x.phone||'-'}}</td><td>{{x.accountNumber||'-'}}</td><td>{{x.address||'-'}}</td><td>₹{{Number(x.monthlySalary).toFixed(2)}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td class="actions"><button @click="edit(x)">Edit</button><button v-if="x.isActive" class="danger-btn" @click="remove(x)">Delete</button></td></tr></table><Pagination :page="page" :page-count="pageCount" :total="sortedRows.length" :page-size="10" @update:page="page=$event" />
<div v-if="show" class="modal-bg"><div class="modal modal-lg"><button class="modal-close-x" @click="show=false">×</button><h2>{{form.id?'Edit':'Add'}} Staff</h2><div class="form-grid"><label>Staff Name *<input v-model="form.name"></label><label>Designation *<select v-model.number="form.designationId"><option :value="null">Select Designation</option><option v-for="d in designations" :key="d.id" :value="d.id">{{d.name}}</option></select></label><label>Date of Birth<input type="date" v-model="form.dateOfBirth"></label><label>Phone<input v-model="form.phone"></label><label>Account Number<input v-model="form.accountNumber"></label><label>Monthly Salary *<input type="number" min="0" step="0.01" v-model.number="form.monthlySalary"></label><label>Date of Joining<input type="date" v-model="form.dateOfJoining"></label><label class="full">Address<textarea rows="3" v-model="form.address"></textarea></label><label class="toggle-row"><input type="checkbox" v-model="form.isActive"> Active</label></div><div class="modal-actions"><button @click="save">Save</button><button class="secondary" @click="show=false">Cancel</button></div></div></div></template>